eats_classes_dict = {
    "burger": "бургер",
    "strawberry": "клубника",
    "croissant": "круассан",
    "soup": "суп",
    "sushi": "суши/роллы",
    "pizza": "пицца",
    "lasagna": "лазанья",
    "poke": "поке",
    "kebab": "кебаб",
    "donuts": "пончики",
    "sweets": "сладости",
    "salad": "салат",
    "cheese": "сыр",
    "meat": "мясо",
    "carpaccio": "карпаччо",
    "burrata": "буррата",
    "eggplant": "баклажан",
    "tartare": "тартар",
    "mushrooms": "грибы",
    "risotto": "ризотто",
    "seafood": "морепродукты",
    "nuggets": "наггетсы",
    "crepes": "блины",
    "baked potato": "печеный картофель",
    "toast": "тост",
    "cake": "торт/пирог",
    "nachos": "начос",
    "pork": "свинина",
    "meatballs": "фрикадельки",
    "sandwhich": "сэндвич",
    "gyros": "гирос",
    "shrimp": "креветки",
    "teriyaki": "терияки",
    "ham": "ветчина",
    "cookies": "печенье",
    "sausage": "сосиски",
    "mashed potatoes": "картофельное пюре",
    "brownies": "брауни",
    "bacon": "бекон",
    "eggs": "яйца",
    "fried chicken": "жареная курица",
    "hot dogs": "хот-дог",
    "steak": "стейк",
    "tomato": "помидор",
    "burritos": "буррито",
    "tacos": "тако",
    "bread": "хлеб",
    "banana": "банан",
    "potato chips": "чипсы",
    "cheesecake": "чизкейк",
    "ice cream": "мороженое",
    "pie": "пирог",
    "french fries": "картофель фри",
    "pasta": "паста",
    "khinkali": "хинкали",
    "shawarma": "шаурма",
    "barbecue": "барбекю",
    "sauce": "соус",
    "tom yam": "том ям",
    "khachapuri": "хачапури",
    "baklava": "пахлава",
    "borsch": "борщ",
    "porridge": "каша",
    "buckwheat": "гречка",
    "cottage cheese": "творог",
    "milk": "молоко",
    "pilaf": "плов",
    "wine glass": "вино",
    "beans": "бобы",
    "corn": "кукуруза",
    "breakfast": "завтрак (брекфаст)",
    "lobster": "лобстеры",
    "ravioli": "равиоли",
    "carrot": "морковь",
    "pringles": "чипсы Pringles",
    "curry": "карри",
    "cheesecakes": "сырники",
    "pancakes": "оладушки",
    "pizza and sushi": "сет пицца и суши",
    "mashed potatoes and meatballs": "пюрешка с котлеткой",
    "chak-chak": "чак-чак",
    "chak chak": "чак-чак",
    "stuffed cabbage or cabbage rolls": "голубцы",
    "stuffed pepper": "фаршированый перец",
    "mcflurry": "макфлури",
    "carrot sticks": "морковные палочки",
    "fried pie": "жареный пирожок",
    "burger and french fries": "бургер и картошка фри",
    "nuggets and french fries": "нагетсы и картошка фри",
    "cheese sticks": "сырные палочки",
    "fish roll": "фиш ролл",
    "onion fried rings": "обжаренные кольца лука",
    "vinaigrette": "винегрет",
    "rice": "рис",
    "ginger": "имбирь",
    "wasabi": "васаби",
    "fried rice": "жареный рис",
    "white sauce": "белый соус",
    "quesadilla": "кесадилья",
    "unagi": "unagi",
    "baked fish": "запеченая рыба",
    "noodles": "лапша",
    "honey": "мед",
    "nuts": "орехи",
    "pitaya": "питайя (драконий фрукт)",
    "fish": "рыба",
    "khychin": "хычины",
    "croutons": "гренки",
    "cabbage": "капуста",
    "kimchi": "кимчи",
    "lobio": "лобио",
    "pastrami": "пастрами",
    "pho bo": "фо бо",
    "vietnamese cuisine": "вьетнамская кухня",
    "wok": "вок",
    "ramen": "рамен",
}

fruits_dict = {"apple": "яблоко", "lemon": "лимон", "berries": "ягоды"}
beverage_dict = {
    "beer": "пивчик",
    "coffee": "кофе",
    "lemonade": "лимонад",
    "white wine": "белое вино",
    "red wine": "красное вино",
    "tea": "чай",
    "lipton tea": "чай липтон",
    "mineral water": "минеральная вода",
    "aqua minerale": "аква минерале",
    "juice": "сок",
    "matcha": "чай матча",
    "soy sauce": "соевый соус",
    "white sauce": "белый соус",
    "coca cola": "кока-кола",
    "pepsi": "пепси",
}
plant_dict = {
    "pitaya": "питайя (драконий фрукт)",
    "apple": "яблоко",
    "lemon": "лимон",
    "berries": "ягоды",
    "flowers": "цветы",
}
eats_classes_dict.update(fruits_dict)
eats_classes_dict.update(beverage_dict)
eats_classes_dict.update(plant_dict)

en_dishes_classes = list(eats_classes_dict.keys())

class_name_to_class_dict = dict()
class_name_to_class_dict["food"] = eats_classes_dict
