eats_classes = [
    "burger",
    "strawberry",
    "croissant",
    "fast food",
    "american food",
    "french food",
    "soup",
    "sushi",
    "pizza",
    "lasagna",
    "poke",
    "kebab",
    "donuts",
    "sweets",
    "sugar",
    "salad",
    "cheese",
    "meat",
    "carpaccio",
    "burrata",
    "eggplant",
    "tartare",
    "mushrooms",
    "risotto",
    "seafood",
]
