eats_classes = [
    "burger",
    "strawberry",
    "croissant",
    "fast food",
    "american food",
    "french food",
    "soup",
    "sushi",
    "pizza",
    "lasagna",
    "poke",
    "kebab",
    "donuts",
    "sweets",
    "salad",
    "cheese",
    "meat",
    "carpaccio",
    "burrata",
    "eggplant",
    "tartare",
    "mushrooms",
    "risotto",
    "seafood",
    "nuggets",
    "crepes",
    "baked potato",
    "toast",
    "cake",
    "nachos",
    "pork",
    "meatballs",
    "sandwhich",
    "gyros",
    "lasagna",
    "shrimp",
    "teriyaki",
    "ham",
    "cookies",
    "sausage",
    "mashed potatoes",
    "brownies",
    "bacon",
    "eggs",
    "fried chicken",
    "hot dogs",
    "steak",
    "tomato",
    "burritos",
    "tacos",
    "bread",
    "banana",
    "potato chips",
    "cheesecake",
    "cheese",
    "ice cream",
    "pie",
    "french fries",
    "pasta",
    "khinkali",
    "shawarma",
    "barbecue",
    "sauce",
    "beverage",
]
